name: Node.js CI
 
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [18.x]
 
    steps:
    - uses: actions/checkout@v3
 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
 
    - name: Install dependencies (Backend)
      working-directory: ./backend
      run: npm install
      
    - name: Run tests (Backend)
      working-directory: ./backend
      run: npm test
 
    - name: Install dependencies (Frontend)
      working-directory: ./frontend
      run: npm install
    
    - name: Run tests (Frontend)
      working-directory: ./frontend
      run: npm test
 
    - name: Merge dev into main (if tests pass)
      if: success()  
      run: |
        # Récupérer les derniers changements du dépôt distant
        git fetch origin
        
        # Se placer sur la branche main
        git checkout main
        
        # Réinitialiser main pour qu'elle corresponde à la version distante de main
        git reset --hard origin/main
        
        # Fusionner dev dans main, autoriser la fusion même avec des historiques non liés
        git merge origin/dev --no-ff --no-edit --allow-unrelated-histories
        
        # Pousser les changements sur la branche main du dépôt distant
        git push origin main
      env:
        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
