name: Node.js CI
 
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [18.x]
 
    steps:
    - uses: actions/checkout@v3
 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
 
    - name: Install dependencies (Backend)
      working-directory: ./backend
      run: npm install
      
    - name: Run tests (Backend)
      working-directory: ./backend
      run: npm test
 
    - name: Install dependencies (Frontend)
      working-directory: ./frontend
      run: npm install
    
    - name: Run tests (Frontend)
      working-directory: ./frontend
      run: npm test
 
    - name: Merge dev into main (if tests pass)
      uses: uses: devmasx/merge-branch@1.4.0
          with:
            type: now
            from_branch: dev
            target_branch: main
            github_token: ${{ secrets.GITHUB_TOKEN }}