name: Node.js CI
 
permissions:
  contents: write 
  

on:
  push:
    branches: [ "dev" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [18.x]
 
    steps:
    - uses: actions/checkout@v3
 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
 
    - name: Install dependencies (Backend)
      working-directory: ./backend
      run: npm install
      
    - name: Run tests (Backend)
      working-directory: ./backend
      run: npm test
 
    - name: Install dependencies (Frontend)
      working-directory: ./frontend
      run: npm install
    
    - name: Run tests (Frontend)
      working-directory: ./frontend
      run: npm test
 
    - name: Merge dev into main (if tests pass)
      if: success()  
      run: |
        git fetch origin
        git checkout main
        git config --global user.email "ahkkash.kandasamy@efrei.net"
        git config --global user.name "Ahkkash"
        git merge origin/dev --no-ff --no-edit --allow-unrelated-histories -X theirs --
        git push origin main
      env:
        
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
