name: Docker Workflow
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [18.x]
 
    steps:
    - uses: actions/checkout@v3
 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
 
    - name: Install dependencies (Backend)
      working-directory: ./backend
      run: npm install
      
    - name: Run tests (Backend)
      working-directory: ./backend
      run: npm test
 
    - name: Install dependencies (Frontend)
      working-directory: ./frontend
      run: npm install
    
    - name: Run tests (Frontend)
      working-directory: ./frontend
      run: npm test


    - name: Run end-to-end tests
      working-directory: ./e2e-tests
      run: |
        npm install 
        npm test 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Verify Docker Login
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    
   
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
 
        
    - name: Build and Push Docker Image
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push
    
