name: Docker Workflow
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [18.x]
 
    steps:
    - uses: actions/checkout@v3
 
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
 
    - name: Install dependencies (Backend)
      working-directory: ./backend
      run: npm install
      
    - name: Run tests (Backend)
      working-directory: ./backend
      run: npm test
 
    - name: Install dependencies (Frontend)
      working-directory: ./frontend
      run: npm install
    
    - name: Run tests (Frontend)
      working-directory: ./frontend
      run: npm test
      
    - name: Install Selenium WebDriver and ChromeDriver
      run: |
         npm install selenium-webdriver chromedriver

    - name: Start the Application
      run: |
        cd frontend
        npm run start &
        sleep 10  
    
    - name: Run end-to-end tests
      working-directory: ./e2e-tests
      run: |
        npm install
        npx mocha test.js
 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Verify Docker Login
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    
   
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
 
        
    - name: Build and Push Docker Images
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker build -t $DOCKER_USERNAME/backend ./backend
        docker build -t $DOCKER_USERNAME/frontend ./frontend
        docker push $DOCKER_USERNAME/backend
        docker push $DOCKER_USERNAME/frontend
